Repository openedx/openedx-k8s-harmony, pull requests merged in 2024-04, with the labels that each got.

#57 Add optional OpenFAAS chart
  charts/harmony-chart/Chart.lock
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/templates/NOTES.txt
  charts/harmony-chart/templates/openfaas/namespace.yaml
  charts/harmony-chart/values.yaml
  values-example.yaml
  values-minikube.yaml
Labels: awaiting prioritization, open-source-contribution

#69 Replace Terraform with OpenTofu
  README.md
  infra-examples/aws/README.md
  infra-examples/aws/k8s-cluster/main.tf
  infra-examples/aws/vpc/main.tf
  infra-examples/digitalocean/main.tf
Labels: awaiting prioritization, open-source-contribution, core contributor

#63 chore: providing basic quince support
  tutor-contrib-harmony-plugin/setup.py
  tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/__about__.py
  tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/plugin.py
Labels: open-source-contribution

#70 chore: bump harmony chart version
  charts/harmony-chart/Chart.lock
  charts/harmony-chart/Chart.yaml
Labels: open-source-contribution, core contributor

#71 fix: ensure ES cluster cert name is valid
  charts/harmony-chart/templates/elasticsearch/secrets.yaml
Labels: open-source-contribution, core contributor, waiting for eng review
