Repository openedx/openedx-k8s-harmony, pull requests merged in 2024-03, with the labels that each got.

#65 fix: add missing end-if in notes.txt
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/templates/NOTES.txt
Labels: bug, open-source-contribution, core contributor

#67 Add __init__.py to harmony_search
  tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/__about__.py
  tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/harmony_search/__init__.py
Labels: open-source-contribution

#58 Add optional Velero chart
  charts/harmony-chart/Chart.lock
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/values.yaml
  values-example.yaml
Labels: awaiting prioritization, open-source-contribution, waiting for eng review
