Repository openedx/openedx-k8s-harmony, pull requests merged in 2024-12, with the labels that each got.

#87 feat: add complete example of infrastructure with aws
  infra-examples/aws/eks/eks.tf
  infra-examples/aws/eks/outputs.tf
  infra-examples/aws/eks/provider.tf
  infra-examples/aws/eks/readme.md
  infra-examples/aws/eks/templates/post_bootstrap_user_data.tpl
  infra-examples/aws/eks/values.auto.tfvars.json
  infra-examples/aws/eks/variables.tf
  infra-examples/aws/eks/versions_override.tf
  infra-examples/aws/eks/vpc.tf
Labels: open-source-contribution

#93 feat: add vector with defaults
  charts/harmony-chart/Chart.lock
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/values.yaml
  values-example.yaml
Labels: open-source-contribution

#126 fix: removing cert-manager invalid value
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/values.yaml
Labels: open-source-contribution

#127 fix: adding resources only if right subcharts are enabled
  charts/harmony-chart/Chart.yaml
  charts/harmony-chart/templates/echo.yaml
  charts/harmony-chart/templates/elasticsearch/secrets.yaml
  charts/harmony-chart/templates/opensearch/secrets.yaml
Labels: open-source-contribution

#135 chore: bump harmony chart version
  charts/harmony-chart/Chart.yaml
Labels: maintenance, open-source-contribution

#138 fix: ensure let's encrypt email can be set
  charts/harmony-chart/templates/issuer.yaml
  charts/harmony-chart/values.yaml
Labels: bug, open-source-contribution

#139 chore: bump chart version
  charts/harmony-chart/Chart.yaml
Labels: maintenance, open-source-contribution
